language: python
python:
  - "3.8"
  - "3.10"
  - "3.11"
install:
  - pip install -r swe1Project/requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test
- env


after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: dishaenv
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: dg4355-swe1-app/swe1Project
    branch: main
  skip_cleanup: 'true'
#Outside travis.yml
