language: python
python:
  - "3.8"
  - "3.10"
  - "3.11"

before_install:
  - cd swe1Project
  - pip install "setuptools<59" "wheel"  # Downgrade setuptools to avoid awsebcli issues
  - pip install "awsebcli==3.20.10"  # Use a stable version of awsebcli
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test
- env


after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: dishaenv
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: dg4355-swe1-app/swe1Project
    branch: main
  skip_cleanup: 'true'

  #inside travis.yml
