dist: focal
language: python
python:
  - "3.10"
  - "3.11"

before_install:
  - cd swe1Project
  - pip install --upgrade pip
  - pip install "setuptools<59" "wheel" 
  - pip install "awsebcli==3.20.10" 
install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

# before_script:
#   - python manage.py makemigrations
#   - python manage.py migrate


script:
  - black --check . 
  - flake8 --max-line-length=150 swe1Project/ 
  - coverage run manage.py test 
  - env

after_scripts:
  - coveralls


before_deploy:
  - cd ..  # Move back to the root directory before deployment
  - zip -r deploy.zip swe1Project/
  - pip install awscli
  - echo "Starting AWS Elastic Beanstalk deployment..."
  - echo "AWS Access Key: $AWS_ID"
  - echo "AWS Secret Key: ${AWS_KEY:0:4}********"  # Only show first 4 characters for security
  - aws configure set aws_access_key_id "$AWS_ID"
  - aws configure set aws_secret_access_key "$AWS_KEY"
  - aws configure set default.region "us-east-2"
  - aws configure list
  - ls -lh deploy.zip  # Verify ZIP exists
  - aws s3 ls s3://elasticbeanstalk-us-east-2-639584540069/ 



deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-east-2
  app: swe1Project
  env: dishaenv
  bucket_name: elasticbeanstalk-us-east-2-639584540069
  on:
    repo: Dishagaonkar/dg4355-swe1-app
    branch: main
  skip_cleanup: 'true'
  zip_file: deploy.zip

after_deploy:
  - echo "Deployment finished. Checking AWS status..."
  - aws elasticbeanstalk describe-environments --region us-east-2
  - aws elasticbeanstalk describe-events --region us-east-2 --environment-name dishaenv --max-items 5


